services:
  api1:
    image: ghcr.io/torreslucas13/r2026-fraud-vector-search:haswell
    command: ["/app/api", "/app/index.bin", "/sockets/api1.sock"]
    volumes:
      - sockets:/sockets
    networks: [app]
    ulimits:
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    image: ghcr.io/torreslucas13/r2026-fraud-vector-search:haswell
    depends_on: [api1]
    command: ["/app/api", "/app/index.bin", "/sockets/api2.sock"]
    volumes:
      - sockets:/sockets
    networks: [app]
    ulimits:
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  lb:
    image: ghcr.io/torreslucas13/r2026-fraud-vector-search:haswell
    depends_on: [api1, api2]
    command: ["/app/lb", "9999", "/sockets/api1.sock", "/sockets/api2.sock"]
    volumes:
      - sockets:/sockets
    ports:
      - "9999:9999"
    networks: [app]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"

networks:
  app:
    driver: bridge

volumes:
  sockets:
